- role: system
  content: "You are a helpful programming assistant designed to complete code snippets."
- role: user
  content: |
    Please generate code to complete the following problem:
    ```
    ${prompt}
    ```
